import{a as L,S,i as l}from"./assets/vendor-BIn0hBn5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const $="23587423-82924c7bf0de5f5bd871046c4",P="https://pixabay.com/api/";async function q(t,r=1,s=15){const n=`${P}?key=${$}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${s}`;try{return(await L.get(n)).data}catch(e){throw console.error("❌ Axios error:",e),e}}function v(t){t.innerHTML=""}function A(t,r){const s=t.map(({webformatURL:n,largeImageURL:e,tags:o,likes:i,views:g,comments:b,downloads:w})=>`
    <li class="photo-card">
      <a href="${e}">
        <img src="${n}" alt="${o}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${i}</p>
        <p><b>Views:</b> ${g}</p>
        <p><b>Comments:</b> ${b}</p>
        <p><b>Downloads:</b> ${w}</p>
      </div>
    </li>`).join("");r.insertAdjacentHTML("beforeend",s)}const f=document.querySelector(".loader");function I(){f.style.display="block"}function u(){f.style.display="none"}const R=document.querySelector("#search-form"),d=document.querySelector(".gallery"),a=document.querySelector(".load-more");let m="",c=1;const p=15;let y=0;const E=new S(".gallery a",{captionsData:"alt",captionDelay:250});a.style.display="none";R.addEventListener("submit",async t=>{t.preventDefault();const r=t.currentTarget.elements.searchQuery.value.trim();if(!r){l.warning({message:"Please enter a search term",position:"topRight"});return}m=r,c=1,v(d),a.style.display="none",await h()});a.addEventListener("click",async()=>{c+=1,await h()});async function h(){I();try{const t=await q(m,c,p);if(t.hits.length===0&&c===1){l.info({message:"Sorry, there are no images matching your search request.",position:"topRight"}),a.style.display="none",u();return}A(t.hits,d),E.refresh(),y=t.totalHits,c*p<y?a.style.display="block":(a.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),await O(),x(),u()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"}),u()}}async function O(){const t=d.querySelectorAll("img"),r=Array.from(t).map(s=>new Promise(n=>{s.complete?n():(s.onload=()=>n(),s.onerror=()=>n())}));await Promise.all(r)}function x(){const{height:t}=d.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
