import{a as L,S,i as l}from"./assets/vendor-BIn0hBn5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const $="23587423-82924c7bf0de5f5bd871046c4",P="https://pixabay.com/api/";async function q(t,o=1,a=15){const n=`${P}?key=${$}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${a}`;try{return(await L.get(n)).data}catch(e){throw console.error("❌ Axios error:",e),e}}function v(t){t.innerHTML=""}function x(t,o){const a=t.map(({webformatURL:n,largeImageURL:e,tags:r,likes:i,views:h,comments:b,downloads:w})=>`
    <li class="photo-card">
      <a href="${e}">
        <img src="${n}" alt="${r}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${i}</p>
        <p><b>Views:</b> ${h}</p>
        <p><b>Comments:</b> ${b}</p>
        <p><b>Downloads:</b> ${w}</p>
      </div>
    </li>`).join("");o.insertAdjacentHTML("beforeend",a)}const y=document.querySelector(".loader");function A(){y.style.display="block"}function u(){y.style.display="none"}const C=document.querySelector("#search-form"),d=document.querySelector(".gallery"),s=document.querySelector(".load-more");let m="",c=1;const p=15;let f=0;const I=new S(".gallery a",{captionsData:"alt",captionDelay:250});s.style.display="none";C.addEventListener("submit",async t=>{t.preventDefault();const o=t.currentTarget.elements.searchQuery.value.trim();if(!o){l.warning({message:"Please enter a search term",position:"topRight"});return}m=o,c=1,v(d),s.style.display="none",await g()});s.addEventListener("click",async()=>{c+=1,await g()});async function g(){A(),s.textContent="Loading...",s.disabled=!0;try{const t=await q(m,c,p);if(t.hits.length===0&&c===1){l.info({message:"Sorry, there are no images matching your search request.",position:"topRight"}),s.style.display="none",u();return}x(t.hits,d),I.refresh(),f=t.totalHits,c*p<f?s.style.display="block":(s.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),await R(),E()}catch{l.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{s.textContent="Load more",s.disabled=!1,u()}}async function R(){const t=d.querySelectorAll("img"),o=Array.from(t).map(a=>new Promise(n=>{a.complete?n():(a.onload=()=>n(),a.onerror=()=>n())}));await Promise.all(o)}function E(){const t=d.firstElementChild;if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
